### ISSUE TITLE
Test Fwk: Add ScVal validation trait and fns (U63, Bitset, Symbol)

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-xdr#106]

**Comment by leighmcculloch** [comment]
from @graydon 

> SCV_U63 has to fit in 63 bits.
> SCV_BITSET has to fit in 60 bits.
> obj has to be non-None
> the chars in symbol have to be [a-zA-Z0-9_]

**Comment by leighmcculloch** [comment]
@graydon @jonjove Do you folks have opinions on whether we should run through this validation when parsing XDR, or just offer it as additional functions that a developer can call if they wish? I'm thinking the latter since there could be cases where we introduce new constraints in the future and refusing to deserialize any XDR with validations not satisfied could be too blunt. Wdyt?

**Comment by graydon** [comment]
Yeah I think from a version-safety perspective it's best to do this in core or some part of the host that can be told which version it's expecting to look at.

**Comment by leighmcculloch** [comment]
It sounds like from what you're saying that validation needs to occur independently of deserializing. That makes sense and was where I was leaning.

I've implemented this as an extension function behind a trait in this crate, but that doesn't prevent us from either adding a parameter to the validation function that contains a Stellar protocol version, or by creating a new trait for each protocol where validation changes and having types implement each.
