### ISSUE TITLE
Make XDR types that wrap builtin types type aliases

### ISSUE THREAD

**Issue by leighmcculloch** [stellar/rs-stellar-xdr#8]
XDR typedefs are being rendered as composites but it would make usage of the XDR less verbose if they were rendered as type aliases. There are tradeoffs, but this is worth considering for developer ergonomics.

For example:

Typedefs currently render as composites like so:
```rust
#[derive(Clone, Debug, Hash, PartialEq, Eq)]
pub struct AccountId(pub PublicKey);

#[derive(Clone, Debug, Hash, PartialEq, Eq)]
pub enum PublicKey {
    Ed25519(Uint256),
}

#[derive(Clone, Debug, Hash, PartialEq, Eq)]
pub struct Uint256(pub [u8; 32]);
```

```rust
AccountId(PublicKey::Ed25519(Uint256([...])));
```

Typedefs that render as aliases would reduce some of the verbosity like so:
```rust
pub type AccountId = PublicKey;

#[derive(Clone, Debug, Hash, PartialEq, Eq)]
pub enum PublicKey {
    Ed25519(Uint256),
}

pub type Uint256 = [u8; 32];
```

```rust
AccountId::Ed25519([...]);
```

The benefits are:

1. Convenience and reduced verbosity.

2. It will be easier to support some updates to the XDR that are binary backwards compatible. For example, XDR would allow us to redefine the AccountId as an extension of PublicKey, by adding new cases only valid for AccountIds and not PublicKeys. The AccountId would convert from an alias into a complete definition and most code that uses the AccountId would remain unchanged assuming the existing arms retained their existing names.

There are however tradeoffs:

1. There is a loss of specificity. A developer will be able to pass a PublicKey as an AccountId without any conversion. An AccountId is always a PublicKey so to some degree this is maybe irrelevant, but maybe this allows for some class of bugs.

2. Lack of clarity. As can be seen in the first example above it is very clear that the AccountId is a public key, where-as it is ambiguous in the second example where the AccountId is described as an Ed25519.

3. It will not be possible to add functions or implement traits only for AccountIds. Any added functions will apply to the aliased type also.

**Comment by leighmcculloch** [comment]
An alternative to also consider would be to type alias only types that are clearly identified as builtin types. i.e. Type alias the Uint256, Uint64, Uint32, Int64, Int32, String32, and String64 types.

For example, this would simplify code like:

```diff
- AccountId(PublicKey::Ed25519([...]))
+ AccountId(PublicKey::Ed25519(Uint256([...])))
```

And:

```diff
- SequenceNumber(Int64(234978234))
+ SequenceNumber(234978234)
```

**Comment by graydon** [comment]
xdrpp does `using AccountID = PublicKey` which is equivalent to `typedef`.

(In Rust I think you have a similar pair of options: `type AccountID = PublicKey` or `pub use PublicKey as AccountID`)

Personally I .. somewhat like the extra verbosity and clarity of introducing a wrapper struct / newtype, and I think it'll probably help a bit when it comes to type-directed features in libraries like traits and fuzzing and such.

You could possibly make it a little easier to deal with by defining an `impl From<PublicKey> for AccountID` and/or an `impl AsRef<PublicKey> for AccountID`? Or maybe convenience constructors?

**Comment by leighmcculloch** [comment]
I already have `From<>` implementations backwards and forwards on all types. So there is `impl From<AccountId> for PublicKey` and `impl From<PublicKey> for AccountId`, which I think will be helpful.

I agree about keeping with new types, I think the verbosity has benefits. I think the exception is the types that clearly map to builtin types: Uint32, Int32, etc. I think for those I could do a type alias / use statement. I don't see value in wrapping all u32's in Uint32's.

**Comment by graydon** [comment]
Agreed.

**Comment by leighmcculloch** [comment]
I've created a separate issue for the AsRef impl: https://github.com/stellar/rs-stellar-xdr/issues/13.
