### ISSUE TITLE
Test Fwk: Add function for constructing an ScMap in order

### ISSUE THREAD

**Issue by jonjove** [stellar/rs-stellar-xdr#98]
Semantically, an `ScMap` is an _ordered_ structure to present efficient look-up. This is not encoded in the XDR of course, so it is possible to construct an `ScMap` out of order. Having encountered this issue yesterday, I feel confident it is (a) a foot-gun and (b) quite difficult to debug when it occurs.

Let's make it impossible--or at the very least difficult--to construct an `ScMap` out of order.

**Comment by leighmcculloch** [comment]
>We're using maps for serialization, so they have to serialize in a predictable manner.

The intent with insertion order is that the map is represented in the same order everywhere it exists. When it is created B,A,C, when it is serialized B,A,C, when it is deserialized B,A,C.

**Comment by jonjove** [comment]
But that means I have to know the order in which it was inserted, across different pieces of code. For example, the UDT code ends up "in order" as expected. So to match that anywhere else I would still have to insert it in order.... which is exactly the thing I'm trying to avoid because it requires that external knowledge.

Fundamentally, it's an ordered map. No matter how I insert the items it should have the same structure. If we don't want that, let's just go back to vectors.

**Comment by leighmcculloch** [comment]
>I'm trying to avoid because it requires that external knowledge.

This isn't free and comes at a cost of trying to make a variety of SDKs all produce the same result.

Developers are already accustomed to placing fields in the correct order, because in most programming languages developers have to order arguments on functions in the correct order, so it's not clear to me why this is a unique challenge in this case.

**Comment by jonjove** [comment]
If we think that developers are accustomed to ordered fields, then let's just use vectors.

For context, here's the specific case that tripped me up: `MessageV0 { nonce, domain, parameters }`. When I wrote the serialization, I just went down the list of fields because I was writing into a map. So I inserted `nonce`, then `domain`, then `parameters`. But this isn't in alphabetical order, so it didn't match what the UDT code does. I'm aware of this now, and I doubt it will trip me up again. But it's a perfect foot-gun that will definitely not provide a positive experience.

**Comment by leighmcculloch** [comment]
In your case if maps were serialized in insertion order your intuition would have been correct.

In the XDR maps are just vectors already so I don't think there is anything to change there. In the host we are maybe being too clever with them by making them lexicographically ordered. For efficient lookup we should still probably load them into a map, but we could be using a map implementation that results in consistent roundtrip serialization of any XDR map.

**Comment by leighmcculloch** [comment]
Even if we switch UDTs to use the host vec, we run into this issue if anyone stores a map inside a vec.

**Comment by leighmcculloch** [comment]
@graydon Can maps in the host be changed to preserve the order of the entries in the original XDR array? By preserve the order, I mean that iterating the map should use the original order, inserting into the map should append to the order unless replacing the key, and serializing should use the iteration order.

**Comment by leighmcculloch** [comment]
I think this behavior to sort an ScMap belongs here. I'll look into ways to present this in the API such that the `ScMap` type could never be not sorted.

**Comment by leighmcculloch** [comment]
@graydon did this in #112
